server:
  port: 8081

openai:
  apiKey: 12345
  chatModel: gpt-3.5-turbo
  chatTemperature: 0.7
  chatmaxTokens: 4000
  conversationNumber: 3
  proxyHost: 127.0.0.1
  proxyPort: 10809
  timeout: 300
  isProxy: true
  sk: 1qaz@WSX

